version: "3.6"
services:
  # MiniDLNa - DLNa server
  minidlna:
    container_name: minidlna
    hostname: minidlna
    image: jonasmarquez/minidlna
    restart: always
    privileged: true
    volumes:
      - /mnt/nas/Downloads:/media/video
      - ./minidlna.conf:/etc/minidlna/minidlna.conf:ro
    environment:
      - MINIDLNA_MEDIA_DIR_1=V,/media/video
    network_mode: host
